FROM node:8.11.3-alpine as builder
WORKDIR /app

RUN apk update && \
    yarn global add @vue/cli
COPY package.json .
RUN yarn install
COPY . .

RUN echo "VUE_APP_SOCKET_ORIGIN=http://35.247.18.78:30000/web-socket-server/" > .env.production && \
    echo "VUE_APP_API_ORIGIN=http://35.247.18.78:30000/database-controller/api/v1" >> .env.production && \
    yarn build

FROM nginx:1.15-alpine as deploy
COPY --from=builder /app/dist /usr/share/nginx/html
