FROM node:8.11.3-alpine as builder
WORKDIR /app

RUN apk update && \
    yarn global add @vue/cli

COPY package.json .
RUN yarn install

COPY . .

ENV SERVER_PORT 31420
ENV SERVER_IP_ADDRESS 123.456.789.0
ENV hoge hoge

RUN ["yarn", "build"]






FROM nginx:1.15-alpine
#
# COPY nginx/conf.d /etc/nginx/conf.d
# COPY --from=builder /app/dist /usr/share/nginx/html


ENV hoge hoge


# 関係ないのでこれは無視してください
# ENV PORT=8000
