FROM node:8.11.3-alpine as builder
ENV API_ORIGIN http://35.247.18.78:30008
WORKDIR /app
RUN apk update && \
    yarn global add @vue/cli
COPY package.json .
RUN yarn install
COPY . .

RUN sed -i -e '/^VUE_APP_API_ORIGIN/s/=.*$/=${API_ORIGIN}/' .env.production
RUN yarn build


FROM nginx:1.15-alpine as deploy
COPY --from=builder /app/dist /usr/share/nginx/html
