FROM node:8.11.3-alpine as builder
ENV API_ORIGIN http://35.187.206.173:31420
WORKDIR /app
RUN apk update && \
    yarn global add @vue/cli
COPY package.json .
RUN yarn install
COPY . .
CMD ["sed", "-i", "-e", "'/^VUE_APP_API_ORIGIN/s/=.*$/=${API_ORIGIN}/'", ".env.production"]
CMD ["yarn", "build"]


FROM nginx:1.15-alpine as deploy
COPY --from=builder /app/dist /usr/share/nginx/html
# For google cloud run
ENV PORT 8000

COPY nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
