apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-env-config
data:
  PORT: "{{ .Values.webSocketServer.port }}"
  DC_PORT: "{{ .Values.databaseController.port }}"
  DC_URL: "{{ .Values.databaseController.service.name }}"
  IPU_ENV: {{ .Values.env }}
