apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: {{ .Values.docker.username }}/{{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.client.port }}
          resources:
            requests:
              memory: 5Mi
              cpu: 0m
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
          readinessProbe:
            httpGet:
              port: {{ .Values.client.port }}
              path: /
            successThreshold: 1
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3

      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf
