apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.service.name }}
spec:
  type: {{ .Values.client.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.client.port }}
      targetPort: {{ .Values.client.port }}
      {{- if .Values.client.nordePort }}
      nodePort: {{ .Values.webSocketServer.nodePort }}
      {{- end }}