apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - port: {{ .Values.databaseController.port }}
      nodePort: {{ .Values.databaseController.nodePort }}
      targetPort: {{ .Values.databaseController.port }}
