apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.docker.username}}/{{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.databaseController.port }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-env-config
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 1
            successThreshold: 1
            periodSeconds: 10
            httpGet:
              port: {{ .Values.databaseController.port }}
              path: /api/v1/healthz

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.databaseController.service.name }}
spec:
  type: {{ .Values.databaseController.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.databaseController.port }}
      targetPort: {{ .Values.databaseController.port }}
      {{ if .Values.databaseController.nodePort }}
      nodePort: {{ .Values.databaseController.nodePort }}
      {{ end }}

