version: '2'
services:
  node:
    build:
      context: .
    image: node:11.15.0-alpine
    container_name: mock-server
    hostname: node
    volumes:
      - ".:/src"
    working_dir: /src
    environment:
      - API_ORIGIN="localhost:3000"
    command: [sh, -c, npm install && npm start]
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
