version: '2'
services:
  compiler:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:11.15.0-alpine
    container_name: compiler
    hostname: compiler
    volumes:
      - ".:/src"
    working_dir: /src
    environment:
      - PORT=3001
    command: [sh, -c, npm install && npm start]
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
