docker:
  username: kafuhamada

webSocketServer:
  port: 8008
  nodePort: 30008

databaseController:
  port: 8888
  nodePort: 30888
  configMapName: dc-config

postgres:
  user: ipu
  password: ipu-password
  db: ipu-room
  hostname: postgres
