apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-database-controller
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: database-controller
  template:
    metadata:
      labels:
        app: database-controller
    spec:
      containers:
        - name: database-controller
          image: {{ .Values.docker.username}}/{{ .Values.databaseController.image }}:{{ .Values.databaseController.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.databaseController.port }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-postgres-env-config
            - configMapRef:
                name: {{ .Chart.Name }}-dc-env-config
            - configMapRef:
                name: {{ .Chart.Name }}-global-env-config
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 1
            successThreshold: 1
            periodSeconds: 10
            httpGet:
              port: {{ .Values.databaseController.port }}
              path: /api/v1/healthz

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.databaseController.serviceName }}
spec:
  type: NodePort
  selector:
    app: database-controller
  ports:
    - port: {{ .Values.databaseController.port }}
      nodePort: {{ .Values.databaseController.nodePort }}
      targetPort: {{ .Values.databaseController.port }}

