timeout: 600s

steps:
  # deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-cluster-credentials'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ipu-project-cluster \
        --zone=${_ZONE} \
        --project=${PROJECT_ID}
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'decryption'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        gcloud kms decrypt \
        --key=helm \
        --keyring=gcb \
        --location=global \
        --plaintext-file=helm/values.yaml \
        --ciphertext-file=helm/values.yaml.enc
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'helm'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        ./helm3-alpha-amd64 init \
        && \
        ./helm3-alpha-amd64 lint \
        -f helm/values.yaml \
        --set env=prd \
        helm/reverse-proxy \
        && \
        ( \
        ./helm3-alpha-amd64 template \
        -f helm/values.yaml \
        --set env=prd \
        helm/reverse-proxy \
        | kubectl apply -f - \
        )
    waitFor: ['get-cluster-credentials', 'decryption']
