steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-auth'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        docker login -u ${_DOCKER_USERNAME} -p ${_DOCKER_PASSWORD}
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'pull-image'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        docker pull us.gcr.io/${PROJECT_ID}/ipu-client:latest &&\
        docker pull docker.io/${_DOCKER_USERNAME}/ipu-client-builder:latest
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        cd client && \
        docker build \
        -t docker.io/${_DOCKER_USERNAME}/ipu-client-builder:latest \
        -t docker.io/${_DOCKER_USERNAME}/ipu-client-builder:${REVISION_ID} \
        --cache-from docker.io/${_DOCKER_USERNAME}/ipu-client-builder:latest \
        -f Dockerfile-cd \
        --target builder \
        . && \
        docker build \
        -t us.gcr.io/${PROJECT_ID}/ipu-client:latest \
        -t us.gcr.io/${PROJECT_ID}/ipu-client:${REVISION_ID} \
        --cache-from docker.io/${_DOCKER_USERNAME}/ipu-client-builder:latest \
        --cache-from us.gcr.io/${PROJECT_ID}/ipu-client:latest \
        -f Dockerfile-cd \
        .
    waitFor: ['pull-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        docker push docker.io/${_DOCKER_USERNAME}/ipu-client-builder:latest &&\
        docker push docker.io/${_DOCKER_USERNAME}/ipu-client-builder:${REVISION_ID} &&\
        docker push us.gcr.io/${PROJECT_ID}/ipu-client:latest &&\
        docker push us.gcr.io/${PROJECT_ID}/ipu-client:${REVISION_ID}
    waitFor: ['docker-auth', 'build-image']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        gcloud beta run deploy \
        --allow-unauthenticated \
        --quiet \
        --image=us.gcr.io/cka-practice-kafu/ipu-client \
        --region=us-central1 \
        ipu
    waitFor: ['push-image']
