steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'pull-latest-image'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    docker pull docker.io/${_DOCKER_USERNAME}/${PROJECT_ID}-server:latest \
    || true
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-image'
  args:
  - 'build'
  - '-t'
  - 'docker.io/${_DOCKER_USERNAME}/${PROJECT_ID}-server:${REVISION_ID}'
  - '-t'
  - 'docker.io/${_DOCKER_USERNAME}/${PROJECT_ID}-server:latest'
  - '--cache-from'
  - 'docker.io/${_DOCKER_USERNAME}/${PROJECT_ID}-server:latest'
  - 'web-socket-server/src'
  waitFor: ['pull-latest-image']

- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-login'
  args:
  - 'login'
  - '-u'
  - '${_DOCKER_USERNAME}'
  - '-p'
  - '${_DOCKER_PASSWORD}'
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: 'push-image'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    docker push docker.io/${_DOCKER_USERNAME}/${PROJECT_ID}-server:latest &&\
    docker push docker.io/${_DOCKER_USERNAME}/${PROJECT_ID}-server:${REVISION_ID}
  waitFor: ['docker-login', 'build-image']

# --- deploy ---
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'get-cluster-credentials'
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - 'ipu-project-cluster'
  - '--zone=${_ZONE}'
  - '--project=${PROJECT_ID}'
  waitFor: ['-']


- name: 'gcr.io/cloud-builders/kubectl'
  id: 'sed-file'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    gcp/kubernetes/web-socket-server/sed.sh ${PROJECT_ID} ${_DOCKER_USERNAME} ${REVISION_ID}
  waitFor: ['push-image']

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'deploy'
  args:
  - 'apply'
  - '-f'
  - 'gcp/kubernetes/web-socket-server'
  waitFor: ['sed-file', 'get-cluster-credentials']

timeout: 1800s
